import {showTreasure} from './treasure.js';
import {validateBank, Expedition} from './engine.js';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let bank=[], game=null, selected=null, config={prize:'Uma surpresa especial espera por você!',seconds:60}, draft=[], editing=0, audio=null, audioOn=false, installEvent=null;
function save(){try{localStorage.setItem('expedicao-v1',JSON.stringify({bank,config}));return true;}catch{$('configMessage').textContent='Salvo nesta sessão. O navegador não permitiu guardar os dados para a próxima visita.';return false;}}
function puzzle(){let defs='',images='',outlines='';for(let r=0;r<2;r++)for(let c=0;c<5;c++){const i=r*5+c,x=c*180,y=r*300;let d=`M ${x} ${y}`;d+=r===0?` h 180`:` h 65 c -20 -40 70 -40 50 0 h 65`;d+=c===4?` v 300`:` v 125 c 40 -20 40 70 0 50 v 125`;d+=r===1?` h -180`:` h -65 c 20 -40 -70 -40 -50 0 h -65`;d+=c===0?` v -300`:` v -125 c 40 20 40 -70 0 -50 v -125`;d+=' Z';defs+=`<clipPath id="p${i}"><path d="${d}"/></clipPath>`;images+=`<image class="piece" id="piece${i}" href="assets/chest.png" width="900" height="600" preserveAspectRatio="xMidYMid slice" clip-path="url(#p${i})"/>`;outlines+=`<path d="${d}" fill="none" stroke="#a49a693b" stroke-width="2"/>`;} $('puzzle').innerHTML=`<svg viewBox="0 0 900 600" aria-hidden="true"><defs>${defs}</defs>${images}${outlines}</svg>`;$('progress').innerHTML=Array.from({length:10},()=>'<span></span>').join('');}
function renderProgress(){const n=game?.pieces||0;$('count').textContent=`${n} de 10 peças`;$('puzzle').setAttribute('aria-label',`Baú: ${n} de 10 peças conquistadas`);for(let i=0;i<10;i++){$(`piece${i}`).classList.toggle('revealed',i<n);$('progress').children[i].classList.toggle('done',i<n);}}
function cards(){for(const card of ['sense','chance','torch']){const q=game?.question;const unavailable=!game||game.status!=='playing';const unsuitable=card==='sense'&&(q?.type!=='multiple'||q?.options.length<=2)||card==='torch'&&!q?.hint;$(card).disabled=unavailable||game?.used[card]||unsuitable;$(card).querySelector('.card-state').textContent=game?.used[card]?(card==='chance'&&game.shield?'Proteção ativa':'Utilizada'):unsuitable&&game?(card==='torch'?'Sem dica cadastrada':'Não se aplica'):'Disponível';}}
function welcome(){game=null;document.body.classList.remove('win','chest-opened');$('stage').textContent='02 / A EXPEDIÇÃO';$('timer').textContent=`${config.seconds}s`;$('timer').classList.remove('urgent');$('feedback').textContent='';$('vaultTitle').textContent='O baú esquecido';$('vaultText').textContent='Cada acerto revela parte do caminho.';$('questionArea').innerHTML=`<p class="eyebrow">SEU DESAFIO COMEÇA AQUI</p><h2>Você consegue<br>desvendar o segredo?</h2><p>Acerte 10 enigmas para reconstruir o baú. Você terá <strong>${config.seconds} segundos</strong> por pergunta e três cartas para ajudar.</p><p>${bank.length} perguntas no diário. Dez serão sorteadas para esta aventura.</p><button class="primary" id="start">Iniciar expedição</button>`;$('start').onclick=start;renderProgress();cards();}
function start(){game=new Expedition(bank,config.seconds,config.prize);$('settings').disabled=true;document.body.classList.remove('win','chest-opened');renderQuestion();}
function renderQuestion(){selected=null;$('feedback').textContent='';$('stage').textContent=`ENIGMA ${String(game.index+1).padStart(2,'0')} / 10`;const q=game.question;$('questionArea').innerHTML=`<h2 tabindex="-1">${esc(q.q)}</h2><form id="answerForm">${q.type==='multiple'?`<div class="options">${q.options.map((o,i)=>`<button type="button" class="option" data-index="${i}" aria-pressed="false"><b>${String.fromCharCode(65+i)}</b><span>${esc(o)}</span></button>`).join('')}</div>`:'<label>Sua resposta<input id="answer" autocomplete="off" required maxlength="500"></label>'}<button class="primary" id="submit" ${q.type==='multiple'?'disabled':''}>Confirmar resposta</button></form><p id="hint" hidden></p>`;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.index);document.querySelectorAll('.option').forEach(o=>{o.classList.toggle('selected',o===b);o.setAttribute('aria-pressed',String(o===b));});$('submit').disabled=false;});$('answerForm').onsubmit=e=>{e.preventDefault();answer();};renderProgress();cards();tick();$('questionArea').querySelector('h2').focus();}
function answer(){if(!game||game.status!=='playing')return;const value=game.question.type==='multiple'?selected:$('answer').value;if(value===null||typeof value==='string'&&!value.trim())return;const result=game.answer(value);if(result==='retry'){$('feedback').textContent='A carta protegeu você! Tente outra resposta. O tempo continua correndo.';if(game.question.type==='multiple'){const b=document.querySelector(`[data-index="${selected}"]`);b.disabled=true;b.classList.remove('selected');b.setAttribute('aria-pressed','false');selected=null;$('submit').disabled=true;}else $('answer').select();cards();return;}if(result==='solved'){renderProgress();cards();$('questionArea').innerHTML=`<p class="eyebrow">FRAGMENTO RECUPERADO</p><h2>O segredo ganha forma.</h2><p>Você conquistou a peça ${game.pieces} de 10. Respire e siga em frente.</p><button class="primary" id="next">Próximo enigma</button>`;$('feedback').textContent='Resposta correta!';$('next').onclick=()=>{game.next();renderQuestion();};return;}finish();}
function finish(){if(!game)return;cards();renderProgress();$('settings').disabled=false;const win=game.status==='won';document.body.classList.toggle('win',win);$('vaultTitle').textContent=win?'O tesouro é seu!':'A expedição chegou ao fim';$('vaultText').textContent=win?'Dez enigmas desvendados. Baú desbloqueado.':'Uma nova aventura espera por você.';$('questionArea').innerHTML=win?'<p class="eyebrow">EXPEDIÇÃO CONCLUÍDA</p><h2>Você encontrou o baú.</h2><p>Todos os fragmentos estão reunidos. Descubra o que espera por você.</p><button id="openChest" class="primary">Abrir o baú</button>':`<p class="eyebrow">EXPEDIÇÃO ENCERRADA</p><h2>${game.status==='timeout'?'O tempo se esgotou.':'Uma resposta mudou o destino.'}</h2><p>Você recuperou ${game.pieces} de 10 peças. Prepare-se e tente novamente.</p><button id="restart" class="primary">Voltar ao início</button>`;$('feedback').textContent='';if(win)$('openChest').onclick=()=>showTreasure(game.prize,()=>{document.body.classList.add('chest-opened');$('puzzle').setAttribute('aria-label','Baú aberto: tesouro conquistado');$('questionArea').innerHTML=`<p class="eyebrow">SEU TESOURO</p><h2>A recompensa da jornada</h2><p class="treasure">${esc(game.prize)}</p><button id="restart" class="primary">Nova expedição</button>`;$('restart').onclick=welcome;});else $('restart').onclick=welcome;}
function tick(){if(game?.status!=='playing')return;game.tick();$('timer').textContent=`${game.remaining()}s`;$('timer').classList.toggle('urgent',game.remaining()<=10);if(game.status==='timeout')finish();}setInterval(tick,150);document.addEventListener('visibilitychange',tick);
for(const card of ['sense','chance','torch'])$(card).onclick=()=>{if(!game?.use(card)){tick();return;}if(card==='sense'){game.hidden.forEach(i=>{document.querySelector(`[data-index="${i}"]`).hidden=true;});if(game.hidden.includes(selected)){selected=null;$('submit').disabled=true;}$('feedback').textContent='O sexto sentido eliminou as outras alternativas.';}if(card==='chance')$('feedback').textContent='Proteção ativa nesta pergunta: você pode errar uma vez. O cronômetro não será reiniciado.';if(card==='torch'){$('hint').hidden=false;$('hint').textContent=`Dica: ${game.question.hint}`;}cards();};
function populate(){ $('questionSelect').innerHTML=draft.map((q,i)=>`<option value="${i}">${i+1}. ${esc(q.q.slice(0,75))}</option>`).join('');$('bankInfo').textContent=`${draft.length} perguntas · ${draft.filter(q=>q.hint).length} com dicas cadastradas`;$('questionSelect').value=String(editing);loadEditor();}
function loadEditor(){const q=draft[editing]||{type:'multiple',q:'',options:['','','',''],correct:0,hint:''};$('editType').value=q.type;$('editQ').value=q.q;$('editOptions').value=(q.options||[]).join('\n');$('editCorrect').value=(q.correct??0)+1;$('editAnswers').value=(q.answers||[]).join('\n');$('editHint').value=q.hint||'';toggleFields();}
function toggleFields(){$('multipleFields').hidden=$('editType').value==='open';$('openFields').hidden=$('editType').value==='multiple';}
$('settings').onclick=()=>{draft=structuredClone(bank);editing=0;$('prize').value=config.prize;$('seconds').value=config.seconds;$('configMessage').textContent='';populate();$('config').showModal();};$('closeConfig').onclick=()=>$('config').close();$('editType').onchange=toggleFields;$('questionSelect').onchange=()=>{editing=Number($('questionSelect').value);loadEditor();};$('newQuestion').onclick=()=>{editing=draft.length;loadEditor();};
$('saveQuestion').onclick=()=>{try{const q={type:$('editType').value,q:$('editQ').value,hint:$('editHint').value};if(q.type==='multiple'){q.options=$('editOptions').value.split('\n');q.correct=Number($('editCorrect').value)-1;}else q.answers=$('editAnswers').value.split('\n');const valid=validateBank(Array(10).fill(q))[0];draft[editing]=valid;populate();$('configMessage').textContent='Pergunta atualizada. Salve a preparação para aplicar.';}catch(e){$('configMessage').textContent=e.message;}};
$('deleteQuestion').onclick=()=>{if(editing>=draft.length)return;if(draft.length<=10){$('configMessage').textContent='Mantenha pelo menos 10 perguntas.';return;}draft.splice(editing,1);editing=0;populate();};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3000000)throw Error('Use um arquivo de até 3 MB.');draft=validateBank(JSON.parse((await file.text()).replace(/^\uFEFF/,'')));editing=0;populate();$('configMessage').textContent='Importação válida. Salve a preparação para usar estas perguntas.';}catch(err){$('configMessage').textContent=err.message;}e.target.value='';};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='perguntas-expedicao.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('configForm').onsubmit=e=>{e.preventDefault();try{const seconds=Number($('seconds').value),prize=$('prize').value.trim();if(!Number.isInteger(seconds)||seconds<5||seconds>3600||!prize)throw Error('Informe um prêmio e um tempo inteiro de 5 a 3.600 segundos.');bank=validateBank(draft);config={seconds,prize};const persisted=save();welcome();if(persisted)$('config').close();}catch(err){$('configMessage').textContent=err.message;}};
$('sound').onclick=async()=>{try{if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();const master=audio.createGain();master.gain.value=.12;master.connect(audio.destination);[55,82.41,110,164.81,220.5].forEach((f,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),lfo=audio.createOscillator(),mod=audio.createGain();osc.type='sine';osc.frequency.value=f;gain.gain.value=.09;lfo.frequency.value=.06+i*.025;mod.gain.value=.04;lfo.connect(mod);mod.connect(gain.gain);osc.connect(gain);gain.connect(master);osc.start();lfo.start();});}if(audioOn)await audio.suspend();else await audio.resume();audioOn=!audioOn;$('sound').textContent=audioOn?'♫ Som ligado':'♫ Som desligado';$('sound').setAttribute('aria-pressed',String(audioOn));}catch{$('feedback').textContent='Áudio indisponível neste navegador.';}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('install').hidden=false;});$('install').onclick=async()=>{if(!installEvent)return;await installEvent.prompt();installEvent=null;$('install').hidden=true;};window.addEventListener('appinstalled',()=>{$('install').hidden=true;});
try{bank=validateBank(await (await fetch('./perguntas.json')).json());try{const stored=JSON.parse(localStorage.getItem('expedicao-v1'));if(stored){bank=validateBank(stored.bank);if(Number.isInteger(stored.config?.seconds)&&stored.config.seconds>=5&&stored.config.seconds<=3600&&typeof stored.config.prize==='string')config=stored.config;}}catch{}puzzle();welcome();}catch(e){$('questionArea').innerHTML='<h2>Não foi possível carregar o diário.</h2><p>Recarregue a página com conexão à internet.</p>';$('feedback').textContent=e.message;$('settings').disabled=true;cards();}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
try{document.modelContext?.registerTool({name:'read_expedition_progress',description:'Lê o progresso atual da expedição sem revelar respostas ou prêmio.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({status:game?.status||'ready',pieces:game?.pieces||0,total:10,seconds:game?.remaining()??config.seconds})});}catch{}

$('previewPrize').onclick=()=>showTreasure($('prize').value.trim() || 'Seu tesouro aparecerá aqui');


